/* generated by tools/sprites/to_lvgl.py - do not edit */
#pragma once
#include "lvgl.h"

extern const lv_image_dsc_t ic_clean;
extern const lv_image_dsc_t ic_feed;
extern const lv_image_dsc_t ic_heart_empty;
extern const lv_image_dsc_t ic_heart_food;
extern const lv_image_dsc_t ic_heart_fun;
extern const lv_image_dsc_t ic_med;
extern const lv_image_dsc_t ic_play;
