/* generated by tools/sprites/to_lvgl.py - do not edit */
#pragma once
#include "lvgl.h"

extern const lv_image_dsc_t ic_clean;
extern const lv_image_dsc_t ic_feed;
extern const lv_image_dsc_t ic_med;
extern const lv_image_dsc_t ic_play;
extern const lv_image_dsc_t ic_sleep;
extern const lv_image_dsc_t ic_water;
extern const lv_image_dsc_t rabbit_drink_0;
extern const lv_image_dsc_t rabbit_drink_1;
extern const lv_image_dsc_t rabbit_drink_2;
extern const lv_image_dsc_t rabbit_drink_3;
extern const lv_image_dsc_t rabbit_eat_0;
extern const lv_image_dsc_t rabbit_eat_1;
extern const lv_image_dsc_t rabbit_eat_2;
extern const lv_image_dsc_t rabbit_eat_3;
extern const lv_image_dsc_t rabbit_egg;
extern const lv_image_dsc_t rabbit_idle_0;
extern const lv_image_dsc_t rabbit_idle_1;
extern const lv_image_dsc_t rabbit_idle_2;
extern const lv_image_dsc_t rabbit_idle_3;
extern const lv_image_dsc_t rabbit_idle_4;
extern const lv_image_dsc_t rabbit_idle_5;
extern const lv_image_dsc_t rabbit_idle_6;
extern const lv_image_dsc_t rabbit_idle_7;
extern const lv_image_dsc_t rabbit_sleep_0;
extern const lv_image_dsc_t rabbit_sleep_1;
