/* generated by tools/sprites/to_lvgl.py - do not edit */
#pragma once
#include "lvgl.h"

extern const lv_image_dsc_t ic_clean;
extern const lv_image_dsc_t ic_feed;
extern const lv_image_dsc_t ic_feed_s;
extern const lv_image_dsc_t ic_happy;
extern const lv_image_dsc_t ic_happy_s;
extern const lv_image_dsc_t ic_med;
extern const lv_image_dsc_t ic_play;
