#!/usr/bin/env python3
"""Clean PNGs -> LVGL C arrays plus a sprites.h index.

Runs LVGL's own LVGLImage.py (RGB565A8, memory-mappable from flash) over every
PNG in --in and writes <name>.c into --out, then a sprites.h listing every
`lv_image_dsc_t`. Nothing here is hand-edited afterwards.

  python3 tools/sprites/to_lvgl.py --in assets/sprites --out firmware/main/sprites

LVGLImage.py needs pypng + Pillow + lz4 (see requirements.txt).
"""
import argparse
import subprocess
import sys
from pathlib import Path

DEFAULT_LVGLIMAGE = "firmware/managed_components/lvgl__lvgl/scripts/LVGLImage.py"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="indir", default="assets/sprites")
    ap.add_argument("--out", dest="outdir", default="firmware/main/sprites")
    ap.add_argument("--lvgl-image", default=DEFAULT_LVGLIMAGE)
    args = ap.parse_args()

    indir = Path(args.indir)
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    pngs = sorted(indir.glob("*.png"))
    if not pngs:
        print(f"no PNGs in {indir}", file=sys.stderr)
        return 1

    names = []
    for p in pngs:
        subprocess.run(
            [sys.executable, args.lvgl_image, "--ofmt", "C", "--cf", "RGB565A8",
             "--name", p.stem, "-o", str(outdir), str(p)],
            check=True,
        )
        names.append(p.stem)
        print(f"converted {p.name} -> {outdir / (p.stem + '.c')}")

    (outdir / "sprites.h").write_text(
        "/* generated by tools/sprites/to_lvgl.py - do not edit */\n"
        "#pragma once\n"
        '#include "lvgl.h"\n\n'
        + "".join(f"extern const lv_image_dsc_t {n};\n" for n in names)
    )
    print(f"{len(names)} sprite(s) -> {outdir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
